- name: Dotfiles Playbook setup - Work
  hosts: localhost
  gather_facts: true

  vars:
    # playbook_dir - for location of Ansible playbook :)
    home_directory: "{{ ansible_env.HOME }}"
    XDG_CONFIG_HOME: "{{ home_directory }}/.dotfiles-configs"
    pi_hole_dotfiles:
      - fzf
      - nvim
      - zsh
      - git

  tasks:
    # Submodules - shell script
    
    # Pre-symlink setup
    - name: Update all apt packages
      ansible.builtin.apt:
        name: "*"
        state: latest
      become: true

    - name: Check if zsh command is executable
      command: "which zsh"
      register: zsh_check
      ignore_errors: true

    - name: Install zsh if not installed
      ansible.builtin.apt:
        name: zsh
      become: true
      when: "'zsh' not in zsh_check.stdout"

    - name: Display XDG_CONFIG_HOME
      debug: 
        msg: "The XDG_CONFIG_HOME env variable is set to: {{ XDG_CONFIG_HOME }}"

    - name: Create XDG_CONFIG_HOME directory if it does not exists
      ansible.builtin.file:
        path: "{{ XDG_CONFIG_HOME }}"
        state: directory
        recurse: yes
        mode: '0755'

    # <Strictly> Soft Symlinks
    - name: Symlink - .zshenv
      ansible.builtin.file:
        src: "{{ playbook_dir }}/.zshenv"
        dest: "{{ home_directory }}/.zshenv"
        state: link
        force: no
      become: yes

    - name: Symlinks - Pi-Hole setup
      ansible.builtin.file:
        src: "{{ playbook_dir }}/dotfiles/{{ item }}"
        dest: "{{ XDG_CONFIG_HOME }}/{{ item }}"
        state: link
        force: no
      loop: "{{ pi_hole_dotfiles }}"

    # Post-symlink setup
    # - name: Install Pokemon-Colorscripts
    #   script: "{{ playbook_dir }}/colorscripts-setup.sh"
    #   become: true
