- name: Dotfiles Playbook setup - Work
  hosts: localhost
  gather_facts: true

  vars:
    # playbook_dir - for location of Ansible playbook :)
    work_dotfiles:
      - fzf
      - nvim
      - zsh

  tasks:
    # Submodule

    - name: Update all apt packages
      ansible.builtin.apt:
        name: "*"
        state: latest
      become: true

    - name: Check if zsh command is executable
      command: "which zsh"
      register: zsh_check
      ignore_errors: true

    - name: Install zsh if not installed
      ansible.builtin.apt:
        name: zsh
      when: "'zsh' not in zsh_check.stdout"

    - name: Lookup XDG_CONFIG_HOME
      ansible.builtin.set_fact:
        XDG_CONFIG_HOME: "{{ lookup('ansible.builtin.env', 'XDG_CONFIG_HOME')}}"

    - name: Set XDG_CONFIG_HOME if not defined
      ansible.builtin.set_fact:
        XDG_CONFIG_HOME: "{{ lookup('ansible.builtin.env', 'HOME') }}/.dotfiles-configs"
      register: XDG_CONFIG_HOME_RESULT
      when: XDG_CONFIG_HOME is not defined

    - name: Display XDG_CONFIG_HOME
      debug: 
        msg: "The XDG_CONFIG_HOME env variable is set to: {{ XDG_CONFIG_HOME }}"

    - name: Create XDG_CONFIG_HOME if it does not exists
      ansible.builtin.file:
        path: "{{ XDG_CONFIG_HOME }}"
        state: directory
        recurse: yes

    # <Strictly> Soft Symlinks
    - name: Symlink - .zshenv
      ansible.builtin.file:
        src: "{{ playbook_dir }}/.zshenv"
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.zshenv"
        state: link
        force: no

    - name: Symlink - General setup
      ansible.builtin.file:
        src: "{{ playbook_dir }}/dotfiles/{{ item }}"
        dest: "{{ XDG_CONFIG_HOME }}"
        state: link
        force: no
      loop: "{{ work_dotfiles }}"