- name: Dotfiles Playbook setup - Work
  hosts: localhost
  gather_facts: true

  vars:
    # playbook_dir - for location of Ansible playbook :)
    XDG_CONFIG_HOME: "{{ lookup('ansible.builtin.env', 'HOME') }}/.dotfiles-configs"
    work_dotfiles:
      - fzf
      - nvim
      - zsh

  tasks:
    # Pre-symlink setup
    - name: Update all apt packages
      ansible.builtin.apt:
        name: "*"
        state: latest
      become: true

    - name: Check if zsh command is executable
      command: "which zsh"
      register: zsh_check
      ignore_errors: true

    - name: Install zsh if not installed
      ansible.builtin.apt:
        name: zsh
      become: true
      when: "'zsh' not in zsh_check.stdout"

    - name: Display XDG_CONFIG_HOME
      debug: 
        msg: "The XDG_CONFIG_HOME env variable is set to: {{ XDG_CONFIG_HOME }}"

    - name: Create XDG_CONFIG_HOME directory if it does not exists
      ansible.builtin.file:
        path: "{{ XDG_CONFIG_HOME }}"
        state: directory
        mode: '0755'

    # <Strictly> Soft Symlinks
    - name: Symlink - .zshenv
      ansible.builtin.file:
        src: "{{ playbook_dir }}/.zshenv"
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.zshenv"
        state: link
        force: yes

    - name: Symlinks - Work setup
      ansible.builtin.file:
        src: "{{ playbook_dir }}/dotfiles/{{ item }}"
        dest: "{{ XDG_CONFIG_HOME }}/{{ item }}"
        state: link
        force: no
      loop: "{{ work_dotfiles }}"

    # Post-symlink setup
    - name: Install Pokemon-Colorscripts
      script: "{{ playbook_dir }}/shell-scripts/colorscripts-setup.sh"
      become: true
