- name: Dotfiles Playbook setup - Work
  hosts: localhost
  gather_facts: true

  vars:
    # playbook_dir - (magic variable) for location of Ansible playbook :)
    home_directory: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    XDG_CONFIG_HOME: "{{ home_directory }}/.dotfiles-configs"
    work_dotfiles:
      - fzf
      - nvim
      - zsh

  tasks:
    # Pre-symlink setup
    - name: Display XDG_CONFIG_HOME
      debug: 
        msg: "The XDG_CONFIG_HOME env variable is set to: {{ XDG_CONFIG_HOME }}"

    - name: Create XDG_CONFIG_HOME directory if it does not exists
      ansible.builtin.file:
        path: "{{ XDG_CONFIG_HOME }}"
        state: directory
        recurse: yes
        mode: '0755'

    # <Strictly> Soft Symlinks
    - name: Symlink - .zshenv
      ansible.builtin.file:
        src: "{{ playbook_dir }}/.zshenv"
        dest: "{{ home_directory }}/.zshenv"
        state: link
        force: no

    - name: Symlinks - Work setup
      ansible.builtin.file:
        src: "{{ playbook_dir }}/dotfiles/{{ item }}"
        dest: "{{ XDG_CONFIG_HOME }}/{{ item }}"
        state: link
        force: no
      loop: "{{ work_dotfiles }}"